name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Gh0sT-7/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIVITY_TOKEN }}
